#! /bin/bash

if [ -z $1 ]
then
    echo "Usage: $0 <ip> <port> <workdir> <chunks dir> <media_name> [force]"
    exit 1
fi

wget -T 15 -t 2 -O /dev/null -q     "http://$1:$2/play?mo=$5"
let RES=$?
let EXPECTED_RES=0
echo "RES: $RES"
echo "EXPECTED_RES: $EXPECTED_RES"
if [ $EXPECTED_RES -ne $RES ] || [ "$6" == "force" ]
then
  echo "Rebooting fluunt-server" 
  date >> /var/log/fluunt/flunnt-server-reboot.log
  killall -u fluunt -s 9
  sleep 5
  echo "Executing: /usr/bin/python /opt/fluunt/tools/fluunt-server --loglevel 20 -i 0.0.0.0 -p $2 -T 15 -M 25 -c 4 -w $3 -C $4 -L /var/log/fluunt/flunnt-server.log"
  ( su -c "/usr/bin/python /opt/fluunt/tools/fluunt-server --loglevel 20 -i 0.0.0.0 -p $2 -T 15 -M 25 -c 4 -w $3 -C $4 -L  /var/log/fluunt/flunnt-server.log" fluunt ) > /dev/null 2>&1 &
fi

exit 0

